# ios/Podfile ------------------------------------------------
require_relative '../node_modules/react-native/scripts/react_native_pods'


platform :ios, '15.6'
prepare_react_native_project!

target 'eWonic' do
  config = use_native_modules!               # RN auto-linking (BLE-PLX, etc.)


  use_react_native!(
    path:           config[:reactNativePath],
    app_path:       "#{Pod::Config.instance.installation_root}/..",
    fabric_enabled: false
  )

  post_install do |installer|
    react_native_post_install(installer, config[:reactNativePath])
    installer.pods_project.targets.each do |t|
      t.build_configurations.each do |c|
        c.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.6'
      end
    end
  end
end